apiVersion: v1
kind: Service
metadata:
  name: service-utilisateur
spec:
  selector:
    app: service-utilisateur
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
